import Image from "next/image";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { SeoContent } from "@/lib/content";
import { FaqAccordion, type FaqPair } from "@/components/seo/FaqAccordion";

// ─── Types ────────────────────────────────────────────────────────────────────

type TextSection = { type: "text"; heading: string; rawHeading: string; body: string };
type FaqSection = { type: "faq"; heading: string; rawHeading: string; pairs: FaqPair[] };
type Section = TextSection | FaqSection;

// ─── Content parser ───────────────────────────────────────────────────────────

function cleanHeading(raw: string): string {
  // Strip "Section N — " or "Section N: " prefix generated by the prompt template
  return raw.replace(/^section\s+\d+\s*[—–:-]+\s*/i, "").trim();
}

function parseFaqPairs(body: string): FaqPair[] {
  const pairs: FaqPair[] = [];
  const blocks = body.split(/\n(?=\*\*Q[:\s])/);
  for (const block of blocks) {
    const m = block.match(/^\*\*Q[^*]*?:\s*([\s\S]+?)\*\*\s*\n([\s\S]+)/);
    if (m) pairs.push({ q: m[1].replace(/\*+$/, "").trim(), a: m[2].trim() });
  }
  return pairs;
}

function parseContent(markdown: string): Section[] {
  // Remove a leading duplicate H1 if the model echoed it as a ## heading
  const raw = markdown.replace(/^## [^\n]+\n/, "");
  const chunks = raw.split(/(?=^## )/m).filter((s) => s.trim());

  return chunks.map((chunk): Section => {
    const nl = chunk.indexOf("\n");
    const rawHeading = chunk.slice(0, nl === -1 ? undefined : nl).replace(/^## /, "").trim();
    const heading = cleanHeading(rawHeading);
    const body = nl === -1 ? "" : chunk.slice(nl + 1).trim();

    if (/faq|frequently asked/i.test(rawHeading)) {
      const pairs = parseFaqPairs(body);
      if (pairs.length > 0) return { type: "faq", heading, rawHeading, pairs };
    }

    return { type: "text", heading, rawHeading, body };
  });
}

// ─── Section config ───────────────────────────────────────────────────────────

type SectionTheme = {
  icon: string;
  iconBg: string;
  accent: string;
  badge: string;
};

const THEMES: Record<string, SectionTheme> = {
  problem:  { icon: "⚡", iconBg: "bg-red-50",     accent: "border-red-400",     badge: "bg-red-50 text-red-700"     },
  pain:     { icon: "⚡", iconBg: "bg-red-50",     accent: "border-red-400",     badge: "bg-red-50 text-red-700"     },
  handle:   { icon: "📋", iconBg: "bg-amber-50",   accent: "border-amber-400",   badge: "bg-amber-50 text-amber-700" },
  today:    { icon: "📋", iconBg: "bg-amber-50",   accent: "border-amber-400",   badge: "bg-amber-50 text-amber-700" },
  manual:   { icon: "📋", iconBg: "bg-amber-50",   accent: "border-amber-400",   badge: "bg-amber-50 text-amber-700" },
  easibill: { icon: "🚀", iconBg: "bg-blue-50", accent: "border-blue-500", badge: "bg-blue-50 text-blue-700" },
  solv:     { icon: "🚀", iconBg: "bg-blue-50", accent: "border-blue-500", badge: "bg-blue-50 text-blue-700" },
  start:    { icon: "🎯", iconBg: "bg-indigo-50",  accent: "border-indigo-400",  badge: "bg-indigo-50 text-indigo-700" },
  get:      { icon: "🎯", iconBg: "bg-indigo-50",  accent: "border-indigo-400",  badge: "bg-indigo-50 text-indigo-700" },
};

const DEFAULT_THEME: SectionTheme = {
  icon: "📌", iconBg: "bg-zinc-50", accent: "border-zinc-300", badge: "bg-zinc-100 text-zinc-600",
};

function getTheme(heading: string): SectionTheme {
  const lower = heading.toLowerCase();
  for (const [key, theme] of Object.entries(THEMES)) {
    if (lower.includes(key)) return theme;
  }
  return DEFAULT_THEME;
}

// ─── Hero image ───────────────────────────────────────────────────────────────

const HERO_PHOTOS = [
  { id: "photo-1587854692152-cbe660dbde88", alt: "Pharmacy shelves with medicines" },
  { id: "photo-1576091160399-112ba8d25d1d", alt: "Medicine pills and capsules" },
  { id: "photo-1584308666744-24d5c474f2ae", alt: "Medicine packaging" },
  { id: "photo-1559757148-5c350d0d3c56", alt: "Pharmacist at counter" },
  { id: "photo-1584982751601-97dcc096659c", alt: "Pharmacy interior" },
  { id: "photo-1563013544-824ae1b704d3", alt: "Medical billing documents" },
];

function pickHero(slug: string) {
  let h = 5381;
  for (let i = 0; i < slug.length; i++) h = ((h << 5) + h) ^ slug.charCodeAt(i);
  return HERO_PHOTOS[Math.abs(h) % HERO_PHOTOS.length];
}

function readingTime(content: string) {
  return Math.max(1, Math.round(content.split(/\s+/).length / 200));
}

// ─── Props ────────────────────────────────────────────────────────────────────

type ArticleProps = { page: SeoContent; relatedPages: SeoContent[] };

// ─── Component ───────────────────────────────────────────────────────────────

export function Article({ page, relatedPages }: ArticleProps) {
  const sections = parseContent(page.content);
  const hero = pickHero(page.slug);
  const mins = readingTime(page.content);

  return (
    <div className="bg-zinc-50">

      {/* ── Hero ── */}
      <div className="relative h-80 w-full overflow-hidden sm:h-[28rem]">
        <Image
          src={`https://images.unsplash.com/${hero.id}?w=1400&h=600&fit=crop&q=80&auto=format`}
          alt={hero.alt}
          fill
          priority
          sizes="100vw"
          className="object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-zinc-950/90 via-zinc-950/50 to-zinc-950/10" />
        <div className="absolute bottom-0 left-0 right-0 px-6 pb-10 sm:px-12">
          <div className="mx-auto max-w-4xl">
            <div className="flex flex-wrap items-center gap-2">
              <span className="rounded-full bg-blue-600 px-3 py-1 text-xs font-semibold uppercase tracking-widest text-white">
                {page.keyword}
              </span>
              <span className="text-xs text-zinc-400">{mins} min read</span>
            </div>
            <h1 className="mt-3 text-3xl font-extrabold leading-tight text-white sm:text-4xl md:text-[2.8rem]">
              {page.h1}
            </h1>
            <p className="mt-3 max-w-2xl text-sm leading-relaxed text-zinc-300 sm:text-base">
              {page.metaDescription}
            </p>
          </div>
        </div>
      </div>

      {/* ── GST stat strip ── */}
      <div className="border-b border-zinc-200 bg-white shadow-sm">
        <div className="mx-auto grid max-w-4xl grid-cols-2 sm:grid-cols-4">
          {[
            { stat: "12%",  sub: "GST on most medicines",    color: "text-blue-600"    },
            { stat: "0%",   sub: "GST on essential drugs",   color: "text-green-600"   },
            { stat: "11th", sub: "GSTR-1 filing deadline",   color: "text-amber-600"   },
            { stat: "₹40L", sub: "GSTIN mandatory above",    color: "text-red-500"     },
          ].map(({ stat, sub, color }) => (
            <div key={sub} className="flex flex-col items-center border-r border-zinc-100 px-4 py-5 text-center last:border-0">
              <span className={`text-2xl font-black ${color}`}>{stat}</span>
              <span className="mt-1 text-[11px] leading-4 text-zinc-500">{sub}</span>
            </div>
          ))}
        </div>
      </div>

      {/* ── Body ── */}
      <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:gap-10">

          {/* Main content */}
          <div className="min-w-0 flex-1 space-y-6">
            {sections.map((section, idx) => {
              if (section.type === "faq") {
                return (
                  <section key={idx} id="faq" className="scroll-mt-24">
                    <div className="mb-4 flex items-center gap-3">
                      <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-xl">💬</span>
                      <h2 className="text-xl font-bold text-zinc-900 sm:text-2xl">{section.heading}</h2>
                    </div>
                    <FaqAccordion pairs={section.pairs} />
                  </section>
                );
              }

              const theme = getTheme(section.rawHeading);
              return (
                <section
                  key={idx}
                  className={`overflow-hidden rounded-2xl border-l-4 bg-white shadow-sm ${theme.accent}`}
                >
                  {/* Section header */}
                  <div className="flex items-start gap-4 px-6 py-5">
                    <span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-xl ${theme.iconBg}`}>
                      {theme.icon}
                    </span>
                    <div className="flex-1 pt-1">
                      <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-widest ${theme.badge}`}>
                        {section.heading.split(" ").slice(0, 3).join(" ")}
                      </span>
                      <h2 className="mt-1 text-lg font-bold leading-snug text-zinc-900 sm:text-xl">
                        {section.heading}
                      </h2>
                    </div>
                  </div>

                  {/* Divider */}
                  <div className="mx-6 border-t border-zinc-100" />

                  {/* Body — prose typography now works with @tailwindcss/typography */}
                  <div className="px-6 py-5">
                    <div className="prose prose-sm prose-zinc max-w-none prose-headings:font-semibold prose-headings:text-zinc-800 prose-strong:font-semibold prose-strong:text-zinc-900 prose-a:text-blue-700 prose-a:no-underline hover:prose-a:underline prose-li:text-zinc-700 prose-ol:pl-5 prose-ul:pl-5 prose-p:leading-7 prose-p:text-zinc-700">
                      <ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml>
                        {section.body}
                      </ReactMarkdown>
                    </div>
                  </div>
                </section>
              );
            })}
          </div>

          {/* ── Sidebar ── */}
          <aside className="w-full space-y-5 lg:w-64 lg:shrink-0">

            {/* CTA card */}
            <div className="sticky top-6 rounded-2xl bg-gradient-to-br from-blue-600 to-blue-800 p-6 text-white shadow-xl">
              <div className="text-3xl">💊</div>
              <h3 className="mt-3 text-base font-bold leading-snug">
                Automate your pharmacy billing
              </h3>
              <ul className="mt-3 space-y-2 text-sm text-blue-100">
                {["WhatsApp refill reminders", "Bulk GST invoicing", "Expiry tracking", "Multi-store support"].map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <span className="mt-0.5 text-blue-300">✓</span>
                    {f}
                  </li>
                ))}
              </ul>
              <Link
                href="https://easibill.vercel.app/login"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-5 flex items-center justify-center rounded-xl bg-white px-4 py-3 text-sm font-bold text-blue-700 shadow transition hover:bg-blue-50"
              >
                Start free trial →
              </Link>
              <p className="mt-2 text-center text-xs text-blue-200">No credit card required</p>
            </div>

            {/* Jump-to-FAQ */}
            <a
              href="#faq"
              className="flex items-center gap-3 rounded-xl border border-zinc-200 bg-white px-4 py-4 text-sm font-semibold text-zinc-700 shadow-sm transition hover:border-blue-300 hover:text-blue-700"
            >
              <span className="text-xl">💬</span>
              <span>Jump to FAQ</span>
              <span className="ml-auto text-zinc-400">↓</span>
            </a>

            {/* Related pages */}
            {relatedPages.length > 0 && (
              <div className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm">
                <p className="text-[11px] font-bold uppercase tracking-widest text-zinc-400">
                  Related Articles
                </p>
                <ul className="mt-3 space-y-4">
                  {relatedPages.map((rp) => (
                    <li key={rp.slug}>
                      <Link
                        href={`/${rp.slug}`}
                        className="text-sm font-semibold text-zinc-900 transition hover:text-blue-700"
                      >
                        {rp.metaTitle}
                      </Link>
                      <p className="mt-0.5 line-clamp-2 text-xs text-zinc-500">{rp.metaDescription}</p>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Contact */}
            <div className="rounded-xl border border-zinc-200 bg-white px-4 py-4 shadow-sm">
              <p className="text-xs text-zinc-500">Questions? Reach us directly.</p>
              <a
                href="mailto:support@easibill.com"
                className="mt-1 inline-flex items-center gap-1 text-sm font-semibold text-blue-700 hover:underline"
              >
                support@easibill.com →
              </a>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
